# -*- coding: utf-8 -*-
"""Контент лендинга на двух языках. Из него build.py собирает index.html и en/index.html."""

RU = {
"lang": "ru", "other_lang": "en", "other_lang_label": "EN", "other_href": "en/",
"title": "Закон Зевса — «Одиссея» Кристофера Нолана",
"desc": "Ксения, древний закон гостеприимства, как ключ к «Одиссее» Нолана: почему конь — преступление, скитания — приговор, а расправа — суд.",

"nav_act1": "I · Нарушение", "nav_act2": "II · Кара", "nav_act3": "III · Возвращение",
"nav_play": "Интерактив", "nav_src": "Источники", "nav_imax": "Плёнка",
"sound_off": "Звук", "sound_on": "Звук вкл",
"share": "Поделиться", "share_done": "Ссылка скопирована",
"install": "Установить",

"hero_kicker": "Разбор фильма · 2026",
"hero_t1": "Закон", "hero_t2": "Зевса",
"hero_sub": "Нолан снял не приключенческое кино про дорогу домой. Он снял процесс по делу человека, который сломал единственный закон, удерживавший древний мир от распада.",
"hero_f1": "IMAX 70 мм", "hero_f2": "2 ч 52 мин", "hero_f3": "11 минут чтения",
"hero_scroll": "Листайте",

"note1": "Писалось после сеанса на средиземноморском острове — в тех местах, где в пещерах находят черепа карликовых слонов. С одной впадиной посередине, похожей на глазницу. Дальше станет понятно, почему это важно.",

"a1_label": "Акт первый",
"a1_h": "Нарушение",
"a1_sub": "Дар, который был оружием",
"a1_thesis": "Троянский конь у Нолана — не хитрость и не триумф. Это преступление, после которого мир уже не собрать обратно.",

"a1_p1": "Фильм открывается не победой, а обломком: конь, вросший в песок на пустом берегу. Рецензенты сравнили этот кадр с финалом «Планеты обезьян» — памятник, который оказался руиной. Дальше Нолан возвращается к коню трижды, и каждый раз с другой точки зрения: сначала песня аэда на Итаке, потом триумфальный рассказ Менелая в Спарте, и только в конце — исповедь самого Одиссея перед женой. Один предмет проходит путь от легенды к трофею и заканчивает уликой.",
"a1_p2": "Чтобы понять, почему это устроено именно так, нужно одно греческое слово. У греков не было международного права, но был закон крепче любого права — <b>ксения</b>, священное гостеприимство. За ним стоял лично Зевс: обидеть гостя или хозяина значило оскорбить верховного бога. В фильме это названо прямо — <b>закон Зевса</b>. И вся троянская история — история его двойного слома. Сначала Парис украл жену человека, который принимал его как гостя. Потом греки ответили изощрённее: подделали сам жест дарения.",
"a1_p3": "В этом и поворот Нолана. Конь — не остроумная военная хитрость, а святотатство. Дар в этом мире был материальным рукопожатием между чужими людьми, единственным доказательством, что чужак не враг. Конь превратил это доказательство в ложь. И если дару больше нельзя верить, между людьми не остаётся вообще ничего.",
"a1_p4": "Параллель с «Оппенгеймером» здесь не украшение, а конструкция. Тринити — тоже триумф ума, который в момент успеха становится точкой невозврата, и дальше герой живёт внутри последствий, а не после них. Конь — это Тринити Одиссея. Взрыв уже произошёл в первые минуты; оставшиеся два с половиной часа — расходящаяся волна, и первым она накрывает того, кто нажал на кнопку.",

"scene1_c1": "Утро. Греки ушли. На берегу — дар.",
"scene1_c2": "У Гомера этот дар назван словом δόλος — уловка.",
"scene1_c3": "Внутри дара — война.",
"scene1_c4": "«Мы предали всё, что свято между людьми».",
"scene1_src4": "Реплика Одиссея у Нолана · U.S. Catholic",
"scrub_hint": "Листайте — кадр движется",

"q1": "Что бы это ни было, я боюсь данайцев — даже дары приносящих.",
"q1_src": "Лаокоон о коне. Вергилий, «Энеида», песнь II",

"def_word": "ξενία", "def_translit": "ксения",
"def_text": "Обязанность принять чужака: вымыть, накормить, уложить, одарить и отпустить — и не спрашивать имени, пока гость не поел. Гость обязан не причинять дому вреда и однажды ответить тем же. Поручитель сделки — Зевс Ксений, покровитель странников: под лохмотьями нищего может оказаться бог. Поэтому закрыть дверь — не грубость, а святотатство.",
"def_l1": "Парис нарушил ксению — началась война",
"def_l2": "Конь нарушил её снова — пала Троя",
"def_l3": "Полифем нарушает её как хозяин",
"def_l4": "Женихи нарушают её как гости",

"a2_label": "Акт второй",
"a2_h": "Кара",
"a2_sub": "Десять лет чужих порогов",
"a2_thesis": "Приговор устроен с судебной точностью: человек, осквернивший гостеприимство, обречён десять лет от него зависеть.",
"a2_p1": "У Гомера это объяснено через традицию «Возвращений», ностой: боги гневаются на всех ахейцев за то, что они творили при взятии Трои, и разбрасывают победителей по морю. Нолан переводит богословие в психологию — его Одиссея гонит не столько Посейдон, сколько вина, — но конструкция наказания остаётся прежней. Море раз за разом ставит героя в положение просителя у чужой двери. Тот, кто вскрыл чужой дом изнутри дара, теперь сам стучится в чужие дома и целиком зависит от того, чтут ли там закон Зевса.",
"a2_p2": "Пройдите этот маршрут сами. Каждая остановка — экзамен: где-то его сдаёт хозяин, где-то гость.",
"map_hint_desktop": "Нажмите на точку: где это на карте и что там на самом деле",
"map_hint_touch": "Коснитесь точки: где это на карте и что там на самом деле",
"map_intro_h": "Маршрут нарушителя",
"map_intro_p": "Двенадцать остановок между сожжённым городом и домом, расставленных по традиционным отождествлениям: Мессинский пролив, Липарские острова, Гозо, Корфу. Отождествления спорные — но география, в которой их искали, настоящая.",
"choice_law_kept": "Закон уцелел", "choice_law_broken": "Закон нарушен",

"poly_h": "Полифем",
"poly_sub": "зеркало с одним глазом",
"poly_p1": "Циклоп — единственное чудовище фильма, у которого есть лицо. Это принципиально: Полифем не стихия, он хозяин. Одиссей входит в его пещеру незваным и ест его сыр — гость, прямо скажем, так себе. Но Полифем отвечает антигостеприимством абсолютным: в ответ на просьбу о доле странника он ужинает двумя гостями, а вместо гостевого дара обещает съесть Никого последним. Это ксения, вывернутая наизнанку, — и потому циклоп оказывается зеркалом Одиссея: два нарушителя одного закона в одной пещере.",
"poly_p2": "Билл Ирвин играет его без монструозного рыка. Рецензенты заметили, что фильм почти сочувствует циклопу — по формулировке RogerEbert.com, это просто очень большой пастух, в дом которого вломились маленькие воры. В его дом вломились — ещё одна рифма к коню.",
"poly_note_h": "Откуда взялся циклоп",
"poly_note": "В пещерах Средиземноморья находят черепа карликовых слонов: носовая полость посередине читается как гигантская глазница. Палеонтолог Отенио Абель в 1914 году предположил, что миф о циклопе вырос из этих костей. Мифы иногда не выдумывают — их выкапывают.",
"torch_hint": "Проведите факелом",

"name_label": "Механика проклятия",
"name_before": "Никто. Пока у Одиссея нет имени, проклятию некуда лететь.",
"name_btn": "Назвать себя с палубы",
"name_after_sub": "У проклятия появился адрес.",
"name_p": "Хитрость с «Никто» — идеальная анонимность: ослеплённый Полифем кричит, что его убивает Никто, и соседи расходятся. Но, отплывая, Одиссей не выдерживает и называет себя. Это чистый гибрис и роковая сделка: получив имя, циклоп передаёт его отцу-Посейдону, и проклятие обретает точный адрес. Формула проклятия — это буквально сюжет всего оставшегося эпоса: пусть вернётся поздно, сломленным, один, и найдёт беду в собственном доме. Имя оказывается уязвимым местом.",

"scylla_h": "Сцилла и Харибда",
"scylla_sub": "ужас без адреса",
"scylla_p1": "После циклопа с лицом — стихия без лица. У Гомера Сцилла это шесть шей, тройные ряды зубов и голос, похожий на визг щенят. Никакой психологии, никакой предыстории. Красавица-нимфа, которую из ревности превратили в чудовище, — это Овидий, поздняя романтизация, и Нолан её отбрасывает. Его Сцилла — тварь, с которой невозможно договориться, потому что договариваться не с кем.",
"scylla_p2": "Здесь зеркальная рифма к сцене с именем. Полифему можно было назваться и получить проклятие; Сцилле называться бессмысленно. С циклопом Одиссей торговался, хитрил, победил и проиграл. Сцилле он может только заплатить — шесть гребцов за проход, тариф без переговоров. А рядом Харибда, даже не тело, а отсутствие: воронка, дыра в мире. Закон, нарушенный лично и по имени, возвращается силами, у которых нет ни имени, ни лица, ни слуха.",

"a3_label": "Акт третий",
"a3_h": "Возвращение",
"a3_sub": "Расправа как ритуал",
"a3_thesis": "Финал — не месть, а заседание суда, отложенное на двадцать лет.",
"a3_p1": "Конструкция замыкается симметрично. В первом акте гости въехали в город внутри дара и сожрали его изнутри. В третьем женихи — формально тоже гости — годами проедают дом Одиссея: стада, погреб, труд слуг, — а жену держат как приз. Это то же преступление, снятое с другой стороны: ксения, вывернутая уже не хозяином, как у Полифема, а гостем. Антиной у Паттинсона не злодей, он человек, искренне уверенный, что закон Зевса — для слабых. А Пенелопа и Телемах, продолжающие принимать странников в разграбляемом доме, — единственные, кто закон ещё держит.",
"a3_p2": "Поэтому расправа поставлена как ритуал, а не как бойня: тесный зал, лук вместо меча, нищий, на глазах становящийся царём. Грегори Нэджи читает финал так же: избиение женихов — не столько наказание, сколько необходимое восстановление порядка. Рецензенты отмечают, что именно в финальной схватке темы фильма наконец обретают силу. Насилие здесь не освобождает: оно тяжёлое, и чистого катарсиса зрителю не выдают.",
"a3_p3": "Но Гомер честнее жанра, и Нолан идёт за ним. Восстановленный закон немедленно порождает новый цикл: родня убитых берётся за оружие, кровная месть готова крутиться вечно. Эпос обрывает её вмешательством свыше — Афина по воле Зевса накладывает на остров забвение. Амнистия как единственный выход. Древний поэт знал то, что двадцатый век заново открыл на своих руинах: у возмездия нет естественной последней точки, её можно только поставить.",
"q2": "Истинный герой, истинный предмет, центр «Илиады» — это сила.",
"q2_src": "Симона Вейль, «Илиада, или Поэма о силе», 1940",
"a3_p4": "Антивоенная линия фильма — не изобретение Нолана, а самая старая черта источника. Вейль писала своё эссе, пока Францию накрывала война, и увидела у Гомера редкую вещь: силу, которая превращает в вещь любого — и жертву, и победителя, — и поэта, который оплакивает троянцев наравне с греками. Нолан снимает падение Трои именно так: резня снята как ужас, а не как триумф. И циклоп снят с сочувствием. И женихи умирают без аплодисментов.",
"a3_p5": "А Борхес в 1972-м дал рамку, в которой виден масштаб замысла: историй всего четыре — об осаждённом городе, о возвращении, о поиске и о самоубийстве бога. Фильм закрывает три из четырёх. Троя — осаждённый город, Одиссей — возвращение, Телемах, ищущий отца, — поиск. Три из четырёх борхесовских историй — в одном сюжете.",
"open_q": "Может ли человек, сломавший закон, сам его восстановить?",
"open_a": "Гомер отвечает: только через забвение. Нолан отвечает молчанием Пенелопы.",

"play_label": "Проверьте себя",
"x_h": "Пять порогов",
"x_sub": "Ситуации, в которых закон Зевса ещё работает — только называется иначе. У каждой есть прямой аналог в фильме.",
"x_step": "Порог", "x_of": "из",
"x_next": "Дальше", "x_verdict": "Вердикт", "x_again": "Пройти заново",
"x_score": "Итог",

"tl_h": "Двадцать лет против шести недель",
"tl_sub": "Поэма собрана нелинейно за двадцать семь веков до кино. Посмотрите, как одна жизнь пересобирается порядком рассказа.",
"tl_m1": "Прямая хронология событий", "tl_m2": "Как рассказывает Гомер", "tl_m3": "Как смонтировал Нолан",
"tl_n1": "Если выстроить события подряд: десять лет войны и десять лет пути, из которых восемь Одиссей провёл в плену чужого гостеприимства — семь у Калипсо, год у Цирцеи. На собственно приключения приходится около двух лет.",
"tl_n2": "Поэма начинается с конца истории: кризис на Итаке, потом Калипсо отпускает героя, и лишь затем все знаменитые приключения идут флешбэком — как рассказ гостя за чужим столом. Действие поэмы занимает шесть недель.",
"tl_n3": "Фильм начинается с руины коня, настоящее — кризис на Итаке и путь Телемаха, прошлое всплывает вложенными флешбэками. К коню Нолан возвращается трижды, каждый раз с другой точки зрения.",

"bo_h": "Цена возвращения",
"bo_sub": "Бюджеты и мировые сборы всех фильмов Нолана. «Одиссея» за две недели превысила итоговые сборы «Оппенгеймера» в США и Канаде за весь прокат.",
"bo_budget": "Бюджет", "bo_gross": "Сборы", "bo_table": "Показать таблицу",
"bo_note": "Данные на 1 августа 2026 года: свыше 720 млн долларов, прокат продолжается — цифра устаревает быстрее этой страницы. Сборы прошлых фильмов даны с учётом перевыпусков, поэтому в разных источниках цифры расходятся.",
"bo_live": "прокат идёт",

"qz_h": "Гомер или не Гомер",
"qz_sub": "Многое из того, что все «знают» об «Одиссее», придумано не Гомером. Отличите оригинал от позднейших наслоений.",
"qz_yes": "Гомер", "qz_no": "Не Гомер",
"qz_stmt": "Утверждение", "qz_next": "Дальше", "qz_result": "Итог", "qz_again": "Ещё раз",

"fin_h": "Что теперь понятно",
"fin_1h": "Что сделал Нолан",
"fin_1p": "Перевернул моральную оптику мифа. Конь стал преступлением, скитания приговором, расправа судом. И взял у поэмы нелинейный порядок рассказа, который был там с самого начала.",
"fin_2h": "Почему ксения — ключ",
"fin_2p": "Каждый узел сюжета это сделка гостя и хозяина: Парис, конь, Полифем, Цирцея, феаки, женихи. Кто прочёл фильм через ксению, тому не нужно объяснять, за что наказан герой.",
"fin_3h": "Почему это о нас",
"fin_3p": "Гостеприимство — минимальный договор, на котором держится всё остальное: доверие к чужаку, святость дара, предел мести. Фильм о том, как легко его порвать и как трудно собрать заново. В 2026 году это не археология.",
"note2": "А если смотреть это на острове, где в пещерах лежат черепа слонов ростом с пони, легко поверить, что мифы не выдумывают. Их находят — на берегу, после шторма, полузарытыми в песок. Как коня в первом кадре.",

"imax_label": "Отступление о плёнке",
"imax_h": "Почему семьдесят миллиметров",
"imax_sub": "Кадр размером с ладонь",
"imax_lead": "«Одиссея» заявлена как первый полнометражный фильм, целиком снятый камерами IMAX 15/70. Это не строчка в пресс-релизе, а решение, которое меняет то, как вы физически видите изображение.",
"imax_p1": "Начать стоит с площади кадра. В обычной 35-миллиметровой камере кадр занимает примерно двадцать два на шестнадцать миллиметров — площадь ногтя. Кадр IMAX это семьдесят на сорок восемь: почти в десять раз больше эмульсии на каждый снимок. Плёнка идёт сквозь камеру не вертикально, а горизонтально, и на один кадр приходится пятнадцать перфораций вместо четырёх. Отсюда и странное соотношение сторон 1,43 к одному — кадр почти квадратный, и в зале он занимает не полосу перед вами, а всё поле зрения, включая периферию.",
"imax_p2": "Цена такого кадра — расход. При двадцати четырёх кадрах в секунду плёнка летит сквозь камеру со скоростью около ста метров в минуту: стандартная кассета заканчивается примерно за три минуты. На «Одиссее» за девяносто один съёмочный день израсходовали более двух миллионов футов — это свыше шестисот километров плёнки.",
"grain_h": "Зерно против пикселя",
"grain_lead": "Здесь начинается главное непонимание. Цифровое изображение и плёнку принято сравнивать по числу K — 4K, 8K, 18K. Но это сравнение некорректно в самой своей основе.",
"grain_p1": "Цифровой сенсор — это жёсткая сетка. Ячейки одинакового размера, выстроенные рядами, и они не двигаются: каждый кадр снимается через одну и ту же решётку. У такой структуры есть жёсткий потолок — то, что мельче ячейки, просто не существует. А регулярность сетки порождает собственные артефакты: на мелком повторяющемся узоре появляется муар, которого в реальности нет.",
"grain_p2": "Плёнка устроена принципиально иначе. Изображение на ней складывается из кристаллов галогенида серебра — разного размера, разбросанных случайно, без всякого порядка. И — это ключевое — в каждом следующем кадре они расположены по-новому. Сетки нет, значит нет и потолка: деталь мельче отдельного кристалла всё равно оставляет след, статистически, через плотность зёрен вокруг. Муара тоже нет, потому что нечему войти в резонанс. А глаз за секунду усредняет двадцать четыре разных зерновых рисунка и достраивает то, чего не было ни в одном отдельном кадре.",
"grain_p3": "Поэтому у плёнки нет разрешения в том смысле, в каком оно есть у матрицы. У неё есть структура. Цифры вроде «восемнадцать K» — это попытка перевести одно в другое, и относиться к ним нужно как к оценке, а не к паспортной характеристике: разброс экспертных оценок для IMAX-плёнки идёт от двенадцати до восемнадцати тысяч пикселей по горизонтали. Что можно утверждать твёрдо: площадь эмульсии почти в десять раз больше, а структура — органическая, а не решётчатая.",
"grain_ui": "Двигайте ползунок — меняется увеличение",
"grain_left": "Пиксель",
"grain_right": "Зерно",
"grain_zoom": "Увеличение",
"ig_area_h": "Площадь кадра, в масштабе",
"ig_area_35": "35 мм · 22×16 мм",
"ig_area_imax": "IMAX 15/70 · 69,6×48,5 мм",
"ig_area_note": "Почти десятикратная разница в площади эмульсии на один кадр.",
"ig_res_h": "Сколько это в пикселях, если очень хочется",
"ig_res_note": "Для плёнки это оценка, а не измерение: экспертный разброс идёт от 12K до 18K по горизонтали.",
"ig_n1": "перфораций на кадр", "ig_n2": "соотношение сторон",
"ig_n3": "метров плёнки в минуту", "ig_n4": "километров на фильм",
"fact_label": "Между делом",
"fact1_h": "Три минуты в кассете",
"fact1_p": "Кассета IMAX вмещает около трёх минут съёмки. Для сравнения: на одну карту памяти влезает несколько часов. Каждый дубль здесь стоит физических денег и физического веса — камеру с полной зарядкой носят вдвоём. Это возвращает съёмочной площадке дисциплину, которую цифра успела отменить.",
"fact2_h": "Море было настоящим",
"fact2_p": "Значительную часть морских сцен снимали не в павильоне с синим экраном, а в открытом море и на средиземноморских островах. Нолан объяснял это просто: вода по-настоящему не слушается — и лучше всякой графики показывает, чего эти переходы стоили людям.",
"cap_drag": "Дар тащат к воротам",
"cap_troy": "Крупный план там, где эпос поставил бы панораму",
"cap_bow": "Одиссей и лук",
"cap_sack": "Ночь, в которую всё решилось",
"cap_ramparts": "Те, кто держал закон",
"cap_face": "Молчание Пенелопы",
"cap_imaxset": "Камера IMAX на рельсах",
"cap_nolan": "Режиссёр и мраморная голова",
"tl_hint": "Наведите курсор на событие — увидите, где оно оказывается в каждом из трёх порядков.",
"tl_hint_touch": "Нажмите на событие — увидите, где оно оказывается в каждом из трёх порядков. График листается вбок.",
"tl_read": "проследите линию сверху вниз",
"src_h": "Источники",
"src_p": "Только общедоступные материалы. Часть изображений — кадры и промоматериалы фильма, приведённые в объёме, обычном для критического разбора; часть — иллюстрации, сгенерированные специально для этого текста. Происхождение подписано под каждым изображением. Цитаты приведены короткими фрагментами со ссылкой на источник.",
"src_g1": "Фильм и пресса", "src_g2": "Ксения и разборы", "src_g3": "Гомер и контекст",
"footer": "Независимый некоммерческий разбор. Не связан с Universal Pictures и Syncopy. Изображения, подписанные как созданные ИИ, сделаны специально для этого материала; остальные принадлежат правообладателю и приведены с указанием источника. Цитаты приведены в объёме, необходимом для критического анализа, со ссылками на источники.",
}

EN = {
"lang": "en", "other_lang": "ru", "other_lang_label": "RU", "other_href": "../",
"title": "The Law of Zeus — Christopher Nolan's The Odyssey",
"desc": "Xenia, the ancient law of hospitality, as the key to Nolan's Odyssey: why the horse is a crime, the wandering a sentence, and the slaughter a trial.",

"nav_act1": "I · The Breach", "nav_act2": "II · The Sentence", "nav_act3": "III · The Return",
"nav_play": "Interactive", "nav_src": "Sources", "nav_imax": "Celluloid",
"sound_off": "Sound off", "sound_on": "Sound on",
"share": "Share", "share_done": "Link copied",
"install": "Install",

"hero_kicker": "A reading of the film · 2026",
"hero_t1": "The Law", "hero_t2": "of Zeus",
"hero_sub": "Nolan didn't make an adventure about getting home. He made a trial — of a man who broke the one law that held the ancient world together.",
"hero_f1": "IMAX 70mm", "hero_f2": "2h 52m", "hero_f3": "13 min read",
"hero_scroll": "Scroll",

"note1": "Written after a screening on a Mediterranean island — the kind of place where cave floors still hold the skulls of dwarf elephants. One hollow in the middle of it, exactly where an eye would be. That detail matters later.",

"a1_label": "Act One",
"a1_h": "The Breach",
"a1_sub": "A gift that was a weapon",
"a1_thesis": "In Nolan's hands the Trojan Horse is neither a trick nor a triumph. It is the crime after which the world cannot be put back together.",

"a1_p1": "The film opens not on a victory but on a wreck: the horse sunk into the sand of an empty beach. Critics reached for the ending of Planet of the Apes — a monument revealed as ruin. Nolan then returns to the horse three times, each from a different vantage: a bard's song on Ithaca, Menelaus's triumphant retelling in Sparta, and finally Odysseus's own confession to his wife. One object travels from legend to trophy and ends up as evidence.",
"a1_p2": "To see why it is built this way you need one Greek word. The Greeks had no international law, but they had something stronger — <b>xenia</b>, sacred hospitality. Zeus stood behind it personally: to wrong a guest or a host was to insult the god himself. The film says so outright — <b>the law of Zeus</b>. And the whole Trojan story is the story of breaking it twice. First Paris stole the wife of a man who was hosting him. Then the Greeks answered with something subtler: they forged the gesture of giving itself.",
"a1_p3": "That is Nolan's turn. The horse is not a witty stratagem but a sacrilege. In this world a gift was a physical handshake between strangers, the only proof that a stranger was not an enemy. The horse turned that proof into a lie. And once gifts can no longer be trusted, nothing at all remains between people.",
"a1_p4": "The rhyme with Oppenheimer is structural, not decorative. Trinity is also a triumph of intellect that becomes, at the moment of success, the point of no return — after which the man lives inside the consequences rather than beyond them. The horse is Odysseus's Trinity. The detonation happens in the opening minutes; the remaining two and three-quarter hours are the blast wave, and the first person it reaches is the man who pressed the button.",

"scene1_c1": "Morning. The Greeks are gone. A gift on the shore.",
"scene1_c2": "Homer calls that gift δόλος — a trick.",
"scene1_c3": "Inside the gift: the war.",
"scene1_c4": "\"We violated all that's ever sacred between people.\"",
"scene1_src4": "Odysseus in Nolan's film · U.S. Catholic",
"scrub_hint": "Scroll to play the shot",

"q1": "Whatever it is, I fear the Greeks, even when they bring gifts.",
"q1_src": "Laocoön on the horse. Virgil, Aeneid, Book II",

"def_word": "ξενία", "def_translit": "xenia",
"def_text": "The duty to take a stranger in: wash him, feed him, give him a bed, send him off with a gift — and ask no name until he has eaten. In return the guest must bring the house no harm, and must offer the same welcome if the roles ever reverse. The guarantor is Zeus Xenios, patron of wanderers: the beggar at the door may be a god in rags. Which is why shutting that door is not rudeness but sacrilege.",
"def_l1": "Paris broke xenia — the war began",
"def_l2": "The horse broke it again — Troy fell",
"def_l3": "Polyphemus breaks it as a host",
"def_l4": "The suitors break it as guests",

"a2_label": "Act Two",
"a2_h": "The Sentence",
"a2_sub": "Ten years of other men's doorways",
"a2_thesis": "The punishment is built with judicial precision: the man who defiled hospitality is condemned to spend ten years depending on it.",
"a2_p1": "Homer routes this through the tradition of the Returns — the Nostoi: the gods are angry with all the Achaeans for what they did in the sack of Troy, and scatter the victors across the sea. Nolan translates the theology into psychology — his Odysseus is driven less by Poseidon than by guilt — but the architecture of the sentence is unchanged. The sea puts him, again and again, in the position of a suppliant at someone else's door. The one who broke into a house from inside a gift now knocks at other houses, entirely dependent on whether they keep the law of Zeus.",
"a2_p2": "Walk the route yourself. Every stop is an examination — sometimes the host is being tested, sometimes the guest.",
"map_hint_desktop": "Click a point to see where it is and what is actually there",
"map_hint_touch": "Tap a point to see where it is and what is actually there",
"map_intro_h": "The route of the offender",
"map_intro_p": "Twelve stops between a burned city and home, placed by their traditional identifications: the Strait of Messina, the Aeolian Islands, Gozo, Corfu. The identifications are contested — but the geography people searched in is real.",
"choice_law_kept": "The law held", "choice_law_broken": "The law was broken",

"poly_h": "Polyphemus",
"poly_sub": "a mirror with one eye",
"poly_p1": "The Cyclops is the only monster in the film with a face, and that matters: Polyphemus is not a force of nature, he is a host. Odysseus enters his cave uninvited and eats his cheese — not a model guest. But Polyphemus answers with absolute anti-hospitality: asked for a stranger's due, he dines on two of the guests and offers, as a parting gift, to eat Nobody last. This is xenia turned inside out — which makes the Cyclops a mirror: two breakers of the same law in one cave.",
"poly_p2": "Bill Irwin plays him without the monstrous roar. Reviewers noticed the film's near-sympathy for him: as the RogerEbert.com review puts it, he is simply a very large shepherd whose home is invaded by tiny thieves. His house was broken into — one more rhyme with the horse.",
"poly_note_h": "Where the Cyclops came from",
"poly_note": "Mediterranean caves hold the skulls of dwarf elephants, whose central nasal cavity reads as one enormous eye socket. In 1914 the palaeontologist Othenio Abel proposed that the Cyclops myth grew out of those bones. Some myths aren't invented. They're excavated.",
"torch_hint": "Move the torch",

"name_label": "The mechanics of a curse",
"name_before": "Nobody. While Odysseus has no name, the curse has nowhere to land.",
"name_btn": "Shout your name from the deck",
"name_after_sub": "The curse now has an address.",
"name_p": "The Nobody trick is perfect anonymity: the blinded Cyclops screams that Nobody is killing him, and his neighbours go back to bed. But as he sails away Odysseus can't help himself and gives his real name. It is pure hubris and a fatal transaction: with the name in hand, the Cyclops passes it to his father Poseidon, and the curse acquires a precise address. Its wording is literally the plot of everything that follows — let him come home late, broken, alone, and find trouble in his own house. The name turns out to be the weak point.",

"scylla_h": "Scylla and Charybdis",
"scylla_sub": "terror without an address",
"scylla_p1": "After the monster with a face, a force without one. Homer's Scylla is six necks, three rows of teeth and a voice like a newborn puppy's yelping. No psychology, no backstory. The beautiful nymph transformed out of jealousy is Ovid, a late romanticisation, and Nolan discards it. His Scylla cannot be bargained with because there is no one there to bargain with.",
"scylla_p2": "This mirrors the scene with the name. Polyphemus could be told a name, and he sent a curse back for it; telling Scylla a name is pointless. With the Cyclops, Odysseus haggled, tricked, won and lost. Scylla he can only pay: six oarsmen for passage, a toll with no negotiation. Beside her Charybdis isn't even a body but an absence — a funnel, a hole in the world. A law broken personally, by name, comes back in the form of things with no name, no face and nothing to hear it with.",

"a3_label": "Act Three",
"a3_h": "The Return",
"a3_sub": "Slaughter as ritual",
"a3_thesis": "The finale is not revenge. It is a trial, adjourned for twenty years.",
"a3_p1": "The structure closes with symmetry. In Act One, guests rode into a city inside a gift and devoured it from within. In Act Three the suitors — guests, formally — have spent years eating Odysseus's house: his herds, his wine, his servants, his wife as a prize. The same crime shot from the other side: xenia inverted not by the host, as with Polyphemus, but by the guest. Pattinson's Antinous isn't a villain; he is a man sincerely convinced that the law of Zeus is for the weak. And Penelope and Telemachus, still receiving strangers in a house being stripped bare, are the only ones still holding it.",
"a3_p2": "So the killing is staged as ritual rather than carnage: a confined hall, a bow instead of a sword, a beggar becoming a king in front of you. Gregory Nagy reads it the same way: the slaughter of the suitors is less a punishment than a necessary restoration of order. Reviewers note that the film's themes finally acquire force in that last fight. The violence doesn't liberate: it is heavy, and the film withholds clean catharsis.",
"a3_p3": "But Homer is more honest than the genre, and Nolan follows him. The restored law immediately breeds a new cycle: the families of the dead take up arms, and the blood feud is ready to spin on forever. The epic cuts it off by divine intervention — Athena, on Zeus's order, lays forgetting over the island. Amnesty as the only exit. The ancient poet knew what the twentieth century rediscovered in its own rubble: vengeance has no natural last point; the end has to be imposed.",
"q2": "The true hero, the true subject, the centre of the Iliad, is force.",
"q2_src": "Simone Weil, The Iliad, or the Poem of Force, 1940",
"a3_p4": "The film's anti-war current is not Nolan's invention but the oldest feature of the source. Weil wrote her essay as war closed over France, and found in Homer something rare: force that turns everyone into a thing, victim and victor alike, and a poet who mourns Trojans exactly as he mourns Greeks. Nolan shoots the fall of Troy that way — the massacre shot as horror, not as triumph. The Cyclops with sympathy. The suitors dying without applause.",
"a3_p5": "And in 1972 Borges supplied the frame that shows the scale of the ambition: there are only four stories — a besieged city, a return, a search, and the suicide of a god. The film covers three of the four. Troy is the siege, Odysseus the return, Telemachus looking for his father the search. Three of Borges's four stories inside one plot.",
"open_q": "Can the man who broke the law be the one to restore it?",
"open_a": "Homer answers: only through forgetting. Nolan answers with Penelope's silence.",

"play_label": "Test yourself",
"x_h": "Five thresholds",
"x_sub": "Situations where the law of Zeus still applies, under another name. Each has a direct counterpart in the film.",
"x_step": "Threshold", "x_of": "of",
"x_next": "Next", "x_verdict": "See the verdict", "x_again": "Start over",
"x_score": "Result",

"tl_h": "Twenty years against six weeks",
"tl_sub": "The poem was assembled out of order twenty-seven centuries before cinema. Watch one life reassemble itself by order of telling.",
"tl_m1": "Events in chronological order", "tl_m2": "As Homer tells it", "tl_m3": "As Nolan cuts it",
"tl_n1": "Laid out in order: ten years of war and ten of travel, eight of which Odysseus spends held inside someone else's hospitality — seven with Calypso, one with Circe. The adventures themselves take about two years.",
"tl_n2": "The poem opens at the end of the story: the crisis on Ithaca, then Calypso releasing him, and only then the famous adventures as flashback — a guest's tale at a stranger's table. The poem's own action covers six weeks.",
"tl_n3": "The film opens on the wreck of the horse; the present is the crisis on Ithaca and Telemachus's search, with the past surfacing in nested flashbacks. Nolan returns to the horse three times, each from a different vantage.",

"bo_h": "The cost of coming home",
"bo_sub": "Budgets against worldwide gross for every Nolan film. The Odyssey passed Oppenheimer's entire US and Canada run in two weeks.",
"bo_budget": "Budget", "bo_gross": "Worldwide", "bo_table": "Show as table",
"bo_note": "Figures as of 1 August 2026: past $720 million and still in theatres — the number ages faster than this page. Older totals include re-releases, which is why sources disagree.",
"bo_live": "still running",

"qz_h": "Homer or not Homer",
"qz_sub": "Half of the Odyssey everybody knows comes from somewhere else. Sort the original from the later accretions.",
"qz_yes": "Homer", "qz_no": "Not Homer",
"qz_stmt": "Statement", "qz_next": "Next", "qz_result": "Result", "qz_again": "Start over",

"fin_h": "Where that leaves us",
"fin_1h": "What Nolan did",
"fin_1p": "He reversed the myth's moral perspective. The horse became a crime, the wandering a sentence, the slaughter a trial. And he took from the poem a non-linear order of telling that was there all along.",
"fin_2h": "Why xenia is the key",
"fin_2p": "Every hinge of the plot is a transaction between guest and host: Paris, the horse, Polyphemus, Circe, the Phaeacians, the suitors. Read the film through xenia and nobody needs to explain what the hero is being punished for.",
"fin_3h": "Why it's about us",
"fin_3p": "Hospitality is the minimum contract everything else rests on: trust in a stranger, the sanctity of a gift, a limit on revenge. The film is about how easily it burns and how hard it is to rebuild. In 2026 that isn't archaeology.",
"note2": "And watching it on an island where cave floors hold the skulls of elephants no bigger than ponies, it's easy to believe myths aren't invented. They're found — on a beach, after a storm, half-buried in sand. Like the horse in the opening shot.",

"imax_label": "A digression about celluloid",
"imax_h": "Why seventy millimetres",
"imax_sub": "A frame the size of your palm",
"imax_lead": "The Odyssey is billed as the first feature shot entirely with IMAX 15/70 film cameras. That isn't a press-release line; it's a decision that changes how you physically see the image.",
"imax_p1": "Start with area. In an ordinary 35mm camera the frame is roughly twenty-two by sixteen millimetres — about the size of a fingernail. An IMAX frame is seventy by forty-eight: almost ten times as much emulsion per exposure. The film runs through the camera horizontally rather than vertically, and each frame spans fifteen perforations instead of four. Hence the odd 1.43:1 aspect ratio — a nearly square frame that in the auditorium doesn't sit in a band in front of you but fills your field of view, peripheral vision included.",
"imax_p2": "The price of that frame is consumption. At twenty-four frames a second the film travels through the camera at around a hundred metres a minute: a standard magazine runs out in roughly three minutes. The Odyssey burned through more than two million feet across ninety-one shooting days — over six hundred kilometres of film.",
"grain_h": "Grain against pixel",
"grain_lead": "This is where the central confusion starts. Digital and film are habitually compared by their K numbers — 4K, 8K, 18K. That comparison is wrong at its root.",
"grain_p1": "A digital sensor is a rigid grid. Identical cells in fixed rows, and they never move: every frame is sampled through the same lattice. Such a structure has a hard ceiling — anything finer than one cell simply doesn't exist. And the regularity generates artefacts of its own: fine repeating patterns produce moiré that was never in front of the lens.",
"grain_p2": "Film works on an entirely different principle. Its image is built from silver halide crystals of varying size, scattered at random, in no order at all. And — this is the crucial part — they land differently in every successive frame. No grid means no ceiling: detail finer than a single crystal still leaves a trace, statistically, in the density of grains around it. There is no moiré either, because nothing regular is there to resonate. Meanwhile your eye averages twenty-four different grain patterns per second and reconstructs what no single frame contained.",
"grain_p3": "So film has no resolution in the sense a sensor does. It has a structure. Figures like 18K are an attempt to translate one into the other, and should be read as an estimate rather than a specification: expert estimates for IMAX film run anywhere from 12K to 18K across. What can be stated firmly is that the emulsion area is nearly ten times larger and the structure is organic rather than lattice-based.",
"grain_ui": "Drag the slider to zoom",
"grain_left": "Pixel",
"grain_right": "Grain",
"grain_zoom": "Magnification",
"ig_area_h": "Frame area, to scale",
"ig_area_35": "35mm · 22×16 mm",
"ig_area_imax": "IMAX 15/70 · 69.6×48.5 mm",
"ig_area_note": "Almost a tenfold difference in emulsion area per exposure.",
"ig_res_h": "In pixels, if you insist",
"ig_res_note": "For film this is an estimate, not a measurement: expert figures range from 12K to 18K across.",
"ig_n1": "perforations per frame", "ig_n2": "aspect ratio",
"ig_n3": "metres of film per minute", "ig_n4": "kilometres of stock for the shoot",
"fact_label": "In passing",
"fact1_h": "Three minutes in a magazine",
"fact1_p": "An IMAX magazine holds about three minutes of shooting. For comparison, a digital card on the same shoot holds several hours. Every take here costs real money and real weight — a loaded camera takes two people to carry. It gives a film set back the discipline that digital quietly abolished.",
"fact2_h": "The sea was real",
"fact2_p": "Much of the sea work was shot not on a soundstage against a blue screen but in open water and on Mediterranean islands. Nolan's reasoning was simple: water genuinely refuses to cooperate — and nothing conveys better what those voyages cost the people making them.",
"cap_drag": "The gift hauled to the gate",
"cap_troy": "A close-up where the epic would put a panorama",
"cap_bow": "Odysseus and the bow",
"cap_sack": "The night everything was decided",
"cap_ramparts": "The ones who kept the law",
"cap_face": "Penelope's silence",
"cap_imaxset": "An IMAX camera on a dolly track",
"cap_nolan": "The director and a marble head",
"tl_hint": "Hover over an event to see where it lands in each of the three orderings.",
"tl_hint_touch": "Tap an event to see where it lands in each of the three orderings. The chart scrolls sideways.",
"tl_read": "follow the line downward",
"src_h": "Sources",
"src_p": "Publicly available material only. Some images are film stills and promotional material, quoted at the length criticism normally requires; others were generated for this piece. The provenance is credited under each image. Quotations are short and attributed.",
"src_g1": "The film and the press", "src_g2": "Xenia and readings", "src_g3": "Homer and context",
"footer": "An independent, non-commercial reading. Not affiliated with Universal Pictures or Syncopy. Images credited as AI-generated were made specifically for this piece; the rest belong to the rights holders and are credited in place. Quotations are limited to what critical analysis requires and are attributed to their sources.",
}
