# -*- coding: utf-8 -*-
"""Данные интерактивов: карта, тест, таймлайн, касса, квиз. Оба языка."""

# ─────────────────────────── КАРТА СКИТАНИЙ ───────────────────────────
# id, x, y, ru(name, role, desc, c1, c2, o1k, o1, o2k, o2), en(...)
MAP = [
 dict(id="troy", x=833, y=146, ru=dict(
   name="Троя", role="Точка нарушения",
   place='Гиссарлык, северо-запад Турции', fact='Холм раскопал Генрих Шлиман в 1870-х. Под ним оказалось девять городов, выстроенных один поверх другого; спор о том, какой слой «тот самый», идёт до сих пор.',
   desc="Дар вкатывают в ворота. Ночью греки режут спящий город — сцена снята как ужас, а не как триумф.",
   c1="Спрятаться в коне", c2="Возразить: у войны есть предел",
   o1k="bad", o1="Город горит. Отсюда и реплика, которую приводят рецензенты: «мы предали всё, что свято между людьми». Приговор подписан, осталось узнать срок.",
   o2k="ok", o2="В фильме этого голоса не подал никто. Вейль объясняла почему: сила превращает в вещь и жертву, и победителя."),
  en=dict(name="Troy", role="The breach",
   place='Hisarlik, north-west Turkey', fact='Heinrich Schliemann excavated the mound in the 1870s and found nine cities stacked one on another. Which layer is Homer’s Troy is still disputed.',
   desc="The gift rolls through the gate. That night the Greeks cut down a sleeping city — shot as horror, not as triumph.",
   c1="Hide inside the horse", c2="Say it: even war has a limit",
   o1k="bad", o1="The city burns. This is where reviewers place the line: we violated all that's ever sacred between people. The sentence is signed; only its length is still unknown.",
   o2k="ok", o2="No one in the film says it. Weil explained why: force turns victim and victor alike into things.")),

 dict(id="lotus", x=226, y=451, ru=dict(
   name="Лотофаги", role="Гостеприимство как ловушка",
   place='Джерба, Тунис', fact='Отождествление идёт от Геродота: он писал, что плод лотоса сладок, как финик. Обычным кандидатом считают зизифус (Ziziphus lotus), который растёт на острове и сегодня.',
   desc="Хозяева безупречно радушны: угощают лотосом. Кто попробовал — забывает дом. Ксения без памяти — уже не ксения.",
   c1="Попробовать лотос", c2="Силой увести людей на корабль",
   o1k="bad", o1="Вы остаётесь на этом берегу навсегда — сытым, довольным и никем. Забвение здесь не милость, а растворение.",
   o2k="ok", o2="Так и поступает Одиссей: плачущих гребцов привязывают к скамьям. Иногда человека возвращают домой против его воли."),
  en=dict(name="Lotus-eaters", role="Hospitality as trap",
   place='Djerba, Tunisia', fact='The identification goes back to Herodotus, who wrote that the lotus fruit was as sweet as a date. The usual candidate is the jujube, Ziziphus lotus, which still grows on the island.',
   desc="The hosts are flawlessly kind: they offer lotus. Whoever eats forgets home. Xenia without memory stops being xenia.",
   c1="Taste the lotus", c2="Drag your men back to the ship",
   o1k="bad", o1="You stay on this shore forever — fed, content and nobody. Forgetting here isn't mercy, it's dissolution.",
   o2k="ok", o2="What Odysseus actually does: the weeping crew is tied to the benches. Sometimes a man is brought home against his will.")),

 dict(id="cyclops", x=396, y=265, ru=dict(
   name="Циклоп", role="Экзамен для хозяина, и он провален",
   place='Ачитрецце, Сицилия', fact='У берега торчат из воды базальтовые скалы — Фаральони деи Чиклопи. По преданию, это те самые камни, которыми ослеплённый Полифем швырял вслед кораблю. Склоны Этны начинаются в нескольких километрах, вершина — примерно в двадцати пяти.',
   desc="На просьбу о доле странника Полифем ужинает двумя гостями. Одиссей ослепляет его и называется Никем. Осталось уйти молча.",
   c1="Уйти неузнанным", c2="Назвать себя с палубы",
   o1k="ok", o1="Проклятию некуда лететь: у него нет адреса. Но герой поступит иначе.",
   o2k="bad", o2="Имя уходит Посейдону вместе с просьбой: пусть вернётся поздно, сломленным, один — и найдёт беду в собственном доме."),
  en=dict(name="The Cyclops", role="The host's exam — and the host fails it",
   place='Aci Trezza, Sicily', fact='Basalt stacks rise from the water offshore — the Faraglioni dei Ciclopi, said to be the rocks the blinded Polyphemus hurled after the ship. Etna’s slopes begin a few kilometres inland; the summit is about twenty-five.',
   desc="Asked for a stranger's due, Polyphemus dines on two guests. Odysseus blinds him and calls himself Nobody. All that's left is to leave quietly.",
   c1="Leave as Nobody", c2="Shout your name from the deck",
   o1k="ok", o1="The curse has nowhere to land. But this is not the choice the hero makes.",
   o2k="bad", o2="The name goes to Poseidon with a request attached: let him come home late, broken, alone — and find trouble in his house.")),

 dict(id="aeolus", x=388, y=220, ru=dict(
   name="Эол", role="Идеальный дар",
   place='Липарские острова', fact='Второе их имя — Эоловы: остров Эола античность помещала именно сюда. Архипелаг вулканический, и «мешок ветров» вполне мог родиться из наблюдений за здешними шквалами.',
   desc="Повелитель ветров принимает как положено и вручает прощальный дар: бурдюк, в котором заперты все встречные ветры. Итака уже видна.",
   c1="Довериться команде", c2="Не смыкать глаз и стеречь бурдюк",
   o1k="bad", o1="Спутники развязывают бурдюк — решили, там золото, — и буря отбрасывает корабли назад. Дар, вскрытый из жадности, это маленький троянский конь.",
   o2k="ok", o2="Одиссей так и делал — и уснул в виду родного берега. Тело подводит раньше воли, и закон это учитывает."),
  en=dict(name="Aeolus", role="The perfect gift",
   place='The Aeolian Islands', fact='They carry his name: antiquity put the island of Aeolus here. The archipelago is volcanic, and the bag of winds may well have grown out of its squalls.',
   desc="The lord of winds hosts him properly and hands over a parting gift: a bag holding every contrary wind. Ithaca is already in sight.",
   c1="Trust the crew", c2="Stay awake and guard the bag",
   o1k="bad", o1="They open it — there must be gold — and the storm throws the ships back. A gift opened out of greed is a small Trojan horse.",
   o2k="ok", o2="He did exactly that, and fell asleep within sight of home. The body is weaker than the will; the law accounts for it.")),

 dict(id="laestry", x=159, y=75, ru=dict(
   name="Лестригоны", role="Полная противоположность закону",
   place='Бонифачо, Корсика', fact='Узкая бухта в отвесных известняковых скалах — описание гавани у Гомера совпадает почти буквально: вход как щель, стены сверху.',
   desc="Разведчиков приглашают во дворец и съедают. Гавань оказывается западнёй: великаны забрасывают корабли камнями.",
   c1="Встать в удобной бухте", c2="Оставить корабль снаружи",
   o1k="bad", o1="Из двенадцати кораблей уходит один. Самые тяжёлые потери за весь путь — там, где гостей встречали радушнее всего.",
   o2k="ok", o2="Корабль Одиссея единственный остался снаружи. После циклопа он уже знает, как выглядит пасть, похожая на дверь."),
  en=dict(name="Laestrygonians", role="Total anti-xenia",
   place='Bonifacio, Corsica', fact='A narrow inlet between sheer limestone cliffs. Homer’s description of the harbour matches it almost word for word: a slit for an entrance, walls overhead.',
   desc="The scouts are invited into the palace and eaten. The harbour turns out to be a trap: giants smash the ships with boulders.",
   c1="Moor in the sheltered bay", c2="Keep your ship outside",
   o1k="bad", o1="One ship of twelve gets out. The heaviest losses of the whole voyage, at the place with the warmest welcome.",
   o2k="ok", o2="His ship alone stayed outside. After the Cyclops he knows what a mouth shaped like a door looks like.")),

 dict(id="circe", x=314, y=82, ru=dict(
   name="Цирцея", role="Гостеприимство как превращение",
   place='Монте-Чирчео, Италия', fact='Мыс южнее Рима, который с моря выглядит островом: низкая заболоченная полоса перед ним издали не видна. Отсюда и «остров Цирцеи».',
   desc="Хозяйка угощает — и обращает гостей в свиней: то, что дурной приём делает с человеком, показано буквально. Потом год честного гостеприимства.",
   c1="Остаться на год", c2="Вспомнить про Итаку",
   o1k="ok", o1="Год у Цирцеи — законная передышка. На прощание она объясняет дорогу. Хорошая хозяйка отпускает; этим она и отличается от ловушки.",
   o2k="ok", o2="Напомнить пришлось спутникам, а не герою. Комфорт — самая мягкая из тюрем на этом маршруте."),
  en=dict(name="Circe", role="Hospitality as transformation",
   place='Monte Circeo, Italy', fact='A headland south of Rome that reads as an island from the sea: the low marshy strip in front of it disappears at a distance. Hence "Circe’s island".',
   desc="The hostess feeds her guests and turns them into pigs — bad xenia made literal. Then a year of honest hospitality.",
   c1="Feast for a year", c2="Remember Ithaca",
   o1k="ok", o1="The year is a legitimate rest, and she sends him off with directions. A good host lets you go — that's what separates her from a trap.",
   o2k="ok", o2="It was the crew who had to do the reminding, not the hero. Comfort is the softest prison on this route.")),

 dict(id="sirens", x=367, y=115, ru=dict(
   name="Сирены", role="Испытание знанием",
   place='Ли Галли, близ Позитано', fact='Три островка, которые античность считала домом сирен. В двадцатом веке их купил танцовщик Леонид Мясин, потом — Рудольф Нуреев.',
   desc="У Гомера сирены соблазняют не телом, а знанием: обещают спеть обо всём, включая войну под Троей. Человеку с такой виной это страшнее любой красоты.",
   c1="Привязать себя к мачте", c2="Залить уши воском",
   o1k="ok", o1="Услышать — и не суметь двинуться с места. Похоже на то, как устроено само кино: привязанный зритель, которому поют его собственную вину.",
   o2k="ok", o2="Команда выживает глухой. Тоже выход. Но тогда незачем было и плыть мимо них."),
  en=dict(name="The Sirens", role="A test by knowledge",
   place='Li Galli, near Positano', fact='Three islets antiquity assigned to the Sirens. In the twentieth century the dancer Léonide Massine bought them, and later Rudolf Nureyev.',
   desc="Homer's Sirens seduce with knowledge, not bodies: they promise to sing of everything, the war at Troy included. For a man carrying that guilt it's worse than beauty.",
   c1="Tie yourself to the mast", c2="Fill your ears with wax",
   o1k="ok", o1="To hear it and be unable to move. Which is close to how cinema itself works: a bound audience being sung its own guilt.",
   o2k="ok", o2="The crew survives deaf. Also a strategy — but then there was no point sailing past them.")),

 dict(id="scylla", x=414, y=231, ru=dict(
   name="Сцилла и Харибда", role="Тариф без переговоров",
   place='Мессинский пролив', fact='Харибда — не выдумка: в узком проливе сталкиваются приливные течения двух морей и образуют настоящие водовороты. Местное имя им — «гарофали».',
   desc="С Полифемом можно было торговаться: у него было лицо и имя. У Сциллы шесть безликих шей, у Харибды — только глотка.",
   c1="Держаться Сциллы: потерять шестерых", c2="Держаться Харибды: всё или ничего",
   o1k="ok", o1="Гарантированная цена вместо лотереи. Шестеро гребцов — счёт, который капитан оплачивает молча. Взрослое решение, и спать после него не легче.",
   o2k="bad", o2="Воронка не торгуется: она забирает корабль целиком. Позже, на обломке мачты, он всё-таки попадёт к ней — и выживет один."),
  en=dict(name="Scylla and Charybdis", role="A toll with no negotiation",
   place='The Strait of Messina', fact='Charybdis is not invented: tidal currents of two seas collide in the narrows and throw real whirlpools. Locally they are called garofali.',
   desc="The Cyclops could be bargained with: he had a face and a name. Scylla has six blank necks; Charybdis is nothing but a throat.",
   c1="Keep to Scylla: lose six", c2="Keep to Charybdis: all or nothing",
   o1k="ok", o1="A guaranteed price instead of a lottery. Six oarsmen, a bill the captain pays in silence. The adult decision — and no easier to sleep on.",
   o2k="bad", o2="The funnel doesn't haggle — it takes the whole ship. Later, clinging to a mast, he meets her anyway, and survives alone.")),

 dict(id="helios", x=401, y=250, ru=dict(
   name="Быки Гелиоса", role="Последний экзамен команды",
   place='Тринакия — отождествляют с Сицилией', fact='Древнее имя Сицилии — Тринакрия, «трёхмысная»; тот же знак до сих пор на флаге острова: три ноги, расходящиеся из одной точки. Гомеровскую Тринакию античные читатели считали этим же островом.',
   desc="Запретный остров, священное стадо. Шторм держит корабль месяц, еда кончилась. Команда ждёт, пока капитан уснёт.",
   c1="Голодать, но не трогать стадо", c2="Зарезать быков: боги простят",
   o1k="ok", o1="Единственный способ уцелеть — и выдержал только Одиссей.",
   o2k="bad", o2="Зевс отвечает молнией: корабль в щепки, команда на дне. Святое остаётся святым и тогда, когда очень хочется есть."),
  en=dict(name="The cattle of Helios", role="The crew's final exam",
   place='Thrinakia — identified with Sicily', fact='Sicily’s old name, Trinacria, means "three-pointed", and the flag still carries the emblem: three legs radiating from a centre. Ancient readers took Homer’s Thrinakia for the same island.',
   desc="A forbidden island, a sacred herd. A storm pins the ship for a month and the food runs out. The men wait for the captain to sleep.",
   c1="Starve, but don't touch them", c2="Slaughter them: the gods will forgive",
   o1k="ok", o1="The only way through — and nobody but Odysseus held out.",
   o2k="bad", o2="Zeus answers with lightning: the ship in splinters, the crew on the seabed. The sacred stays sacred even when you're starving.")),

 dict(id="calypso", x=360, y=339, ru=dict(
   name="Калипсо", role="Гостеприимство как плен",
   place='Гозо, Мальта', fact='Над заливом Рамла показывают пещеру Калипсо. Отождествление известно с античности, а Огигия — второе, поэтическое имя острова.',
   desc="Семь лет из десяти. Богиня предлагает бессмертие: идеальные условия и никакой возможности уйти.",
   c1="Остаться: вечность и покой", c2="Уйти: плот, море и смертная жена",
   o1k="bad", o1="Вечность на чужом острове — те же лотофаги, только для одного. Гомер точен: ночами он у богини, днями на берегу, смотрит на воду.",
   o2k="ok", o2="Выбор, на котором держится вся поэма: смертная жизнь дома дороже бессмертия в гостях. Зевс через Гермеса велит отпустить — закон выше богини."),
  en=dict(name="Calypso", role="Hospitality as captivity",
   place='Gozo, Malta', fact='A cave above Ramla Bay is shown as Calypso’s. The identification is ancient — Callimachus already linked Gozo to Ogygia — and Ogygia is still used as the island’s poetic name.',
   desc="Seven of the ten years. The goddess offers immortality: perfect conditions and no way out.",
   c1="Stay: eternity and peace", c2="Leave: a raft, the sea, a mortal wife",
   o1k="bad", o1="Eternity on someone else's island is the lotus for one. Homer is precise: nights with the goddess, days on the shore, staring at water.",
   o2k="ok", o2="The choice that defines the whole work: a mortal life at home over immortality as a guest. Zeus sends Hermes to order her to let him go — the law outranks the goddess.")),

 dict(id="phaeacia", x=584, y=163, ru=dict(
   name="Феаки", role="Образцовый приём",
   place='Корфу', fact='В гавани Палеокастрицы показывают скалу-«корабль феаков»: по Гомеру, разгневанный Посейдон обратил в камень судно, которое довезло Одиссея домой.',
   desc="Безымянного чужака моют, одевают, сажают за стол — и не спрашивают имени, пока он не готов. Его рассказ при этом дворе — четыре песни из двадцати четырёх и самая известная часть поэмы.",
   c1="Назваться сразу", c2="Дождаться, пока спросят",
   o1k="ok", o1="Честно, но здесь так не заведено: сначала стол, потом имя. Аэд поёт о Трое, гость плачет — и только тогда царь спрашивает, кто он.",
   o2k="ok", o2="Так и происходит. Правильно принятый гость сам становится рассказчиком; феаки довозят его домой спящим и не просят платы."),
  en=dict(name="The Phaeacians", role="Xenia at its best",
   place='Corfu', fact='In Paleokastritsa they point out a rock said to be the Phaeacian ship: Poseidon, enraged, turned to stone the vessel that carried Odysseus home.',
   desc="A naked stranger is washed, clothed, seated at the table — and not asked his name until he's ready. His story at that court fills four of the poem's twenty-four books — and nearly all the famous ones.",
   c1="Give your name at once", c2="Wait until they ask",
   o1k="ok", o1="Honest, but not how it's done here: table first, name after. The bard sings of Troy, the guest weeps, and only then does the king ask who he is.",
   o2k="ok", o2="Which is what happens. A properly received guest becomes the storyteller; they sail him home asleep and take no payment.")),

 dict(id="ithaca", x=615, y=223, ru=dict(
   name="Итака", role="Зеркальное нарушение",
   place='Итака, Ионические острова', fact='Совпадение имени не закрывает спор: часть исследователей помещает гомеровскую Итаку на соседнюю Кефалонию, а описание у Гомера подходит к обоим островам лишь отчасти.',
   desc="Дом, где закон вывернут ещё раз: гости пожирают хозяйство и сватаются к хозяйке. Одиссей входит сюда нищим чужаком.",
   c1="Открыться сразу", c2="Войти неузнанным — снова",
   o1k="bad", o1="Против сотни вооружённых — верная смерть. Порядок не возвращают жестом. Его возвращают процедурой: луком, который натянет только хозяин.",
   o2k="ok", o2="Симметрия замкнулась: начал Никем в пещере, заканчивает Никем у своего очага. Только пройдя собственный дом чужаком, он видит, кто держал закон: жена, сын, свинопас и старый пёс."),
  en=dict(name="Ithaca", role="The mirror breach",
   place='Ithaca, the Ionian Islands', fact='The matching name does not settle it: some scholars place Homer\u2019s Ithaca on neighbouring Cephalonia, and Homer\u2019s description only half fits either.',
   desc="A house where the law is inverted again: guests eat the estate and court the lady of the house. Odysseus walks in as a beggar.",
   c1="Reveal yourself now", c2="Enter as Nobody — again",
   o1k="bad", o1="Against a hundred armed men that's suicide. Order isn't restored by a gesture but by procedure — a bow only the owner can string.",
   o2k="ok", o2="The symmetry closes: he began as Nobody in a cave and ends as Nobody at his own hearth. Only by crossing the house as a stranger does he see who kept the law: a wife, a son, a swineherd and an old dog.")),
]

# ─────────────────────────── ТЕСТ НА КСЕНИЮ ───────────────────────────
XENIA = [
 dict(ru=dict(q="Ночь, шторм. В дверь стучит незнакомец — вымокший, без даров, имени не называет.",
    o=[dict(s=2, t="Впустить, усадить к огню, накормить. Вопросы потом.",
            e="Канон. Так принимает даже нищий свинопас Евмей — а гостем оказывается царь. Или бог: на этом стоит вся система."),
       dict(s=1, t="Сперва расспросить через дверь, кто он.",
            e="По-человечески разумно, по закону — провал: расспросы до стола оскорбляют гостя."),
       dict(s=0, t="Не открывать. Время неспокойное.",
            e="Именно так рассуждают циклопы — и поэма показывает, чем это кончается для хозяина пещеры.")]),
   en=dict(q="Night, storm. A stranger knocks — soaked, empty-handed, giving no name.",
    o=[dict(s=2, t="Let him in, seat him by the fire, feed him. Questions later.",
            e="Canonical. Even Eumaeus the swineherd does this — and his guest turns out to be a king. Or a god: the whole system rests on that."),
       dict(s=1, t="Ask through the door who he is first.",
            e="Humanly sensible, legally a failure: questions before the meal insult the guest."),
       dict(s=0, t="Don't open. These are unsettled times.",
            e="Precisely the Cyclops's reasoning — and the poem shows where it leaves the owner of the cave.")])),

 dict(ru=dict(q="Ваш гость живёт у вас седьмой год. Ему пора домой, но с ним хорошо. Вы — Калипсо.",
    o=[dict(s=2, t="Помочь построить плот, дать припасов, показать звёзды.",
            e="Так и кончается: Зевс через Гермеса напоминает, что удерживать гостя — нарушение."),
       dict(s=0, t="Удержать. Предложить бессмертие.",
            e="Гостеприимство без права уйти — плен с хорошим видом."),
       dict(s=1, t="Отпустить, но обидеться и не помогать.",
            e="Половина дела. Ксения — это не «не мешать», а снарядить в дорогу. Прощальный дар — часть закона.")]),
   en=dict(q="Your guest is into his seventh year. It's time he went home, but you like having him. You are Calypso.",
    o=[dict(s=2, t="Help him build a raft, provision it, teach him the stars.",
            e="Which is how it ends: Zeus sends Hermes to remind her that holding a guest is a breach."),
       dict(s=0, t="Keep him. Offer immortality.",
            e="Hospitality without the right to leave is captivity with a good view."),
       dict(s=1, t="Let him go, but sulk and offer nothing.",
            e="Half the job. Xenia isn't 'not obstructing' — it's outfitting the journey. The parting gift is part of the law.")])),

 dict(ru=dict(q="Недавний враг прислал великолепный дар — настолько щедрый, что неловко.",
    o=[dict(s=1, t="Принять с честью: отвергнуть дар значит оскорбить.",
            e="Формально безупречно. Один такой подарок уже приняли с честью — спросите троянцев, чем кончилось."),
       dict(s=2, t="Принять, но сперва посмотреть, что внутри.",
            e="Мудрость выжившего. Доверие — основа ксении, но после Трои закон читают внимательно."),
       dict(s=0, t="Публично отвергнуть и высмеять.",
            e="Теперь нарушитель — вы: отвергнутый дар равен пощёчине. Из таких пощёчин вырастали десятилетние войны.")]),
   en=dict(q="A recent enemy sends a magnificent gift — so generous it's uncomfortable.",
    o=[dict(s=1, t="Accept with honour: refusing a gift is an insult.",
            e="Formally impeccable. One horse was accepted with honour too — ask the Trojans how that went."),
       dict(s=2, t="Accept it, but look inside first.",
            e="The wisdom of a survivor. Trust underwrites xenia, but after Troy you read the law carefully."),
       dict(s=0, t="Refuse it publicly and mock it.",
            e="Now you're the offender: a refused gift is a slap. Ten-year wars have grown from those.")])),

 dict(ru=dict(q="Вы гость в бедном доме. Хозяин делит с вами последний хлеб и отдаёт единственную постель.",
    o=[dict(s=2, t="Принять с благодарностью и запомнить долг.",
            e="Суть ксении — взаимность, отложенная во времени. Евмей делит хлеб с нищим и оказывается за столом царя."),
       dict(s=0, t="Отказаться: неловко объедать бедняка.",
            e="Благородно на вид, оскорбительно по сути: отказ унижает дарителя. Позволить бедному дать — тоже щедрость."),
       dict(s=0, t="Съесть, выспаться, уйти не прощаясь.",
            e="Так ведут себя женихи. Их история заканчивается стрелой в горло.")]),
   en=dict(q="You're a guest in a poor house. Your host shares his last bread and gives you his only bed.",
    o=[dict(s=2, t="Accept gratefully and remember the debt.",
            e="The heart of xenia is reciprocity deferred. Eumaeus shares bread with a beggar and ends up at a king's table."),
       dict(s=0, t="Refuse: it's wrong to eat a poor man's food.",
            e="Noble-looking, insulting in substance: refusal humiliates the giver. Letting the poor give is generosity too."),
       dict(s=0, t="Eat, sleep, leave without a word.",
            e="That's how the suitors behave. Their story ends with an arrow through the throat.")])),

 dict(ru=dict(q="В вашем доме годами живут гости, которые едят ваш скот, опустошают ваш погреб и сватаются к вашей жене.",
    o=[dict(s=1, t="Терпеть: гость священен, Зевс разберётся сам.",
            e="Гость священен, пока остаётся гостем. Гость, проедающий дом, — уже захватчик, и закон его не прикрывает. Хотя терпение Пенелопы тоже часть победы: она выиграла время."),
       dict(s=2, t="Восстановить порядок — и остановить месть.",
            e="Полный ответ Гомера: сначала лук, потом амнистия. Расправа без забвения — просто новый виток войны."),
       dict(s=0, t="Сжечь дом вместе с ними.",
            e="Радикально. Но дом — это и есть то, что вы защищали. Спалив его, вы доделали работу женихов.")]),
   en=dict(q="Guests have lived in your house for years, eating your herds, draining your cellar and courting your wife.",
    o=[dict(s=1, t="Endure it: a guest is sacred, Zeus will handle it.",
            e="A guest is sacred while he is a guest. A guest who devours the house is an occupier, and the law doesn't shield him. Though Penelope's patience is part of the victory too: she bought time."),
       dict(s=2, t="Restore order — and then stop the vengeance.",
            e="Homer's full answer: the bow first, the amnesty after. Slaughter without forgetting is just the next turn of the war."),
       dict(s=0, t="Burn the house down with them inside.",
            e="Radical. But the house is the thing you were defending; burning it finishes the suitors' work for them.")])),
]

XVERDICT = dict(
 ru=[dict(min=8, t="Дом, куда можно постучаться", d="Вы принимаете раньше, чем выясняете, и снаряжаете в дорогу, а не просто не мешаете уйти. Именно это Гомер называет ксенией, и именно на таких домах, по его логике, держится всё остальное."),
     dict(min=5, t="Закон с оговорками", d="Вы соблюдаете правило, пока оно вам не мешает: сначала выясняете, потом принимаете. Так ведёт себя большинство героев поэмы — и именно из этих оговорок вырастает всё, что случается дальше."),
     dict(min=0, t="Сторона Полифема", d="Ваши ответы ближе к логике хозяина пещеры: чужак — прежде всего риск. Это последовательная позиция, и поэма честно показывает, чем она заканчивается для обеих сторон.")],
 en=[dict(min=8, t="A house worth knocking at", d="You receive before you interrogate, and you send a guest off equipped rather than merely letting him go. That is what the poem calls xenia, and in its logic everything else rests on houses like yours."),
     dict(min=5, t="The law, with caveats", d="You keep the rule until it costs you: check first, admit second. Most of the poem's characters behave this way — and everything that follows grows out of exactly those caveats."),
     dict(min=0, t="Polyphemus's side", d="Your answers follow the logic of the cave's host: a stranger is a risk before he is anything else. It is a consistent position, and the poem is honest about where it ends for both parties.")])

# ─────────────────────────── ТАЙМЛАЙН ───────────────────────────
TL = [
 dict(id="war",   ru=("Троянская война","10 лет"),        en=("The Trojan War","10 years"),   cls="war"),
 dict(id="horse", ru=("Конь · падение Трои","ночь"),       en=("The horse · Troy falls","one night"), cls="war"),
 dict(id="cyc",   ru=("Циклоп","дни"),                     en=("The Cyclops","days"),          cls="sea"),
 dict(id="cir",   ru=("Цирцея","1 год"),                   en=("Circe","1 year"),              cls="sea"),
 dict(id="sir",   ru=("Сирены","часы"),                    en=("The Sirens","hours"),          cls="sea"),
 dict(id="scy",   ru=("Сцилла и Харибда","часы"),          en=("Scylla and Charybdis","hours"),cls="sea"),
 dict(id="hel",   ru=("Быки Гелиоса","месяц"),             en=("The cattle of Helios","a month"),  cls="sea"),
 dict(id="cal",   ru=("Калипсо","7 лет"),                  en=("Calypso","7 years"),           cls="sea"),
 dict(id="pha",   ru=("Двор феаков · рассказ","одна ночь"),en=("The Phaeacian court","one night"), cls="tell"),
 dict(id="ith",   ru=("Итака · нищий в доме","дни"),       en=("Ithaca · a beggar at home","days"), cls="home"),
 dict(id="fin",   ru=("Лук · амнистия","финал"),           en=("The bow · the amnesty","finale"), cls="home"),
]
TL_LAYOUT = {
 "chrono": dict(war=(2,1), horse=(30,0), cyc=(38,2), cir=(44,1), sir=(50,3), scy=(55,2), hel=(60,4), cal=(66,1), pha=(76,3), ith=(82,0), fin=(88,4)),
 "homer":  dict(ith=(2,0), cal=(10,2), pha=(18,4), war=(28,1), horse=(36,3), cyc=(46,0), cir=(54,2), sir=(62,4), scy=(70,1), hel=(78,3), fin=(88,0)),
 "nolan":  dict(horse=(2,2), ith=(10,0), war=(20,4), cyc=(30,1), cal=(40,3), cir=(50,0), sir=(58,2), scy=(66,4), hel=(74,1), pha=(82,3), fin=(90,2)),
}

# ─────────────────────────── КАССА ───────────────────────────
BO = [
 dict(n="Following", y=1998, b=0.006, g=0.24,
      ru="Бюджет шесть тысяч долларов, снимали по выходным.", en="A $6,000 budget, shot on weekends."),
 dict(n="Memento", y=2000, b=9, g=40, ru="История, рассказанная задом наперёд.", en="A story told backwards."),
 dict(n="Insomnia", y=2002, b=46, g=113, ru="Единственный фильм Нолана по чужому сценарию.", en="The only Nolan film from someone else's script."),
 dict(n="Batman Begins", y=2005, b=150, g=374, ru="Начало трилогии о Бэтмене и больших бюджетов.", en="The start of the Dark Knight trilogy and of the big budgets."),
 dict(n="The Prestige", y=2006, b=40, g=110, ru="Фильм о цене одержимости. Скромная касса, культовый статус.", en="A film about the price of obsession. Modest gross, cult status."),
 dict(n="The Dark Knight", y=2008, b=185, g=1006, ru="Первый миллиард.", en="The first billion."),
 dict(n="Inception", y=2010, b=160, g=871, ru="Оригинальный сценарий, собравший больше 800 миллионов, — редчайший случай.", en="An original screenplay that grossed over $800 million — a rarity."),
 dict(n="The Dark Knight Rises", y=2012, b=250, g=1115, ru="Пока самый кассовый его фильм.", en="Still his highest-grossing film."),
 dict(n="Interstellar", y=2014, b=165, g=773, ru="Живёт в перевыпусках: цифра растёт до сих пор.", en="Lives on in re-releases; the number is still climbing."),
 dict(n="Dunkirk", y=2017, b=100, g=530, ru="Военный фильм почти без слов и без показанного врага.", en="A war film almost without dialogue, and without a visible enemy."),
 dict(n="Tenet", y=2020, b=200, g=365, ru="Прокат в пандемию.", en="Released into the pandemic."),
 dict(n="Oppenheimer", y=2023, b=100, g=975, ru="Триумф гения как точка невозврата.", en="A triumph of genius that becomes the point of no return."),
 dict(n="The Odyssey", y=2026, b=250, g=721, live=True, ru="Больше 720 миллионов к 1 августа, третья неделя проката.", en="Past $720M by 1 August, in its third week."),
]

# ─────────────────────────── КВИЗ ───────────────────────────
QUIZ = [
 dict(a="not", ru=("Сирены — прекрасные девы с рыбьими хвостами.",
   "У Гомера внешность сирен не описана вовсе, а греческое искусство рисовало их птицами с женскими головами. Рыбий хвост — средневековая путаница. И соблазняют они знанием, а не телом."),
  en=("Sirens are beautiful maidens with fish tails.",
   "Homer never describes their appearance, and Greek art drew them as birds with women's heads. The fish tail is a medieval mix-up. And they seduce with knowledge, not bodies.")),
 dict(a="not", ru=("Троянский конь подробно описан в «Илиаде».",
   "«Илиада» заканчивается до падения Трои — коня в ней нет. В «Одиссее» он упомянут кратко. Канонический рассказ дал Вергилий семь веков спустя."),
  en=("The Trojan Horse is described at length in the Iliad.",
   "The Iliad ends before Troy falls — there's no horse in it. The Odyssey mentions it briefly. The canonical account is Virgil's, seven centuries later.")),
 dict(a="homer", ru=("Цирцея превращает спутников Одиссея в свиней.",
   "Гомер, песнь десятая, без всяких смягчений: угостила, взмахнула жезлом, загнала в свинарник."),
  en=("Circe turns Odysseus's men into pigs.",
   "Homer, Book 10, with no softening: she feeds them, waves the wand, drives them into the sty.")),
 dict(a="not", ru=("Сцилла — нимфа, которую из ревности превратили в чудовище.",
   "У Гомера Сцилла просто ужас: шесть шей, тройные ряды зубов и никакой предыстории. Романтическую версию сочинил Овидий. Нолан выбрал гомеровскую."),
  en=("Scylla was a nymph transformed by a jealous rival.",
   "Homer's Scylla is pure horror: six necks, three rows of teeth, no backstory. The romantic version is Ovid's. Nolan chose Homer's.")),
 dict(a="homer", ru=("Супружеская кровать вырезана из живой оливы и вросла в дом.",
   "Гомер, песнь двадцать третья, и это финальный тест Пенелопы: она велит вынести кровать, и только настоящий муж знает, что вынести её нельзя."),
  en=("The marriage bed is carved from a living olive tree and rooted in the house.",
   "Homer, Book 23 — and it's Penelope's final test: she orders the bed moved, and only the real husband knows it cannot be.")),
 dict(a="not", ru=("«Бойтесь данайцев, дары приносящих» — предупреждение о коне.",
   "Это Лаокоон у Вергилия. Мысль совершенно гомеровская, но строка — латинская и на семь веков моложе."),
  en=("\"Beware of Greeks bearing gifts\" is a warning about the horse.",
   "That's Laocoön in Virgil. The thought is thoroughly Homeric, but the line is Latin and seven centuries younger.")),
 dict(a="homer", ru=("Старый пёс узнаёт вернувшегося хозяина и умирает.",
   "Гомер, песнь семнадцатая. Двадцать лет ожидания, одно движение хвостом, смерть. Самая короткая трагедия в литературе — и она в оригинале."),
  en=("The old dog recognises his returning master and dies.",
   "Homer, Book 17. Twenty years of waiting, one wag of the tail, death. The shortest tragedy in literature, and it's in the original.")),
 dict(a="not", ru=("На Итаку нападают загадочные «народы моря».",
   "У Гомера этого нет: по сообщениям о фильме, историзирующая добавка Нолана. Народы моря реальны — они известны по египетским хроникам бронзового века, современным возможной Троянской войне."),
  en=("Mysterious \"Sea Peoples\" attack Ithaca.",
   "Not in the poem: reported as Nolan's historicising addition. The Sea Peoples themselves are real, known from Bronze Age Egyptian records, contemporaries of a possible Trojan war.")),
 dict(a="not", ru=("Ахиллесова пята: мать держала младенца за пятку, окуная в Стикс.",
   "В «Илиаде» Ахилл уязвим как обычный человек. История со Стиксом пришла от поздних авторов — хрестоматийный «Гомер», которого у Гомера нет."),
  en=("Achilles' heel: his mother dipped him in the Styx holding that heel.",
   "In the Iliad Achilles is as woundable as anyone. The Styx story comes from much later authors — textbook \"Homer\" that isn't in Homer.")),
 dict(a="homer", ru=("Полифем — сын Посейдона, и потому его проклятие работает.",
   "Гомер, песнь девятая. Ослепив сына бога моря, мореплаватель получил десять лет прицельной мести."),
  en=("Polyphemus is Poseidon's son, which is why the curse works.",
   "Homer, Book 9. Blinding the sea god's son bought the sailor ten years of precisely aimed revenge.")),
]

QZ_RESULT = dict(
 ru=[dict(min=9, t="Аэд", d="Вы отличаете Гомера от Вергилия и Овидия с закрытыми глазами — как и положено слепому певцу."),
     dict(min=6, t="Феак", d="Слушали внимательно и плакали в нужных местах. При дворе Алкиноя вас бы дослушали до конца."),
     dict(min=0, t="Лотофаг", d="Похоже, вы попробовали лотоса. Но он отпускает: разделы выше никуда не делись.")],
 en=[dict(min=9, t="A bard", d="You tell Homer from Virgil and Ovid with your eyes shut — as befits a blind singer."),
     dict(min=6, t="A Phaeacian", d="You listened closely and wept in the right places. At Alcinous's court they would have heard you out."),
     dict(min=0, t="A lotus-eater", d="Something you ate, perhaps. But the lotus wears off — the sections above are still there.")])

# ─────────────────────────── ИСТОЧНИКИ ───────────────────────────
SOURCES = [
 ("g1", [
  ("https://variety.com/2026/film/box-office/the-odyssey-700-million-globally-fourth-biggest-movie-1236823343/", "Variety — 700 млн за 12 дней", "Variety — $700M in 12 days"),
  ("https://www.hollywoodreporter.com/movies/movie-news/the-odyssey-box-office-christopher-nolan-opening-success-1236651646/", "THR — рекордный старт", "THR — record opening"),
  ("https://deadline.com/2026/07/box-office-the-odyssey-oppenheimer-record-hadestown-1237006246/", "Deadline — «Одиссея» обошла «Оппенгеймера»", "Deadline — passing Oppenheimer"),
  ("https://www.hollywoodreporter.com/movies/movie-reviews/the-odyssey-review-christopher-nolan-matt-damon-1236647905/", "THR — рецензия Дэвида Руни", "THR — David Rooney's review"),
  ("https://www.rogerebert.com/reviews/the-odyssey-christopher-nolan-matt-damon-film-review-2026", "RogerEbert.com — рецензия", "RogerEbert.com — review"),
  ("https://www.theringer.com/2026/07/23/movies/the-odyssey-christopher-nolan-flashbacks-time-jumping-explained", "The Ringer — структура и три версии коня", "The Ringer — structure and the horse, three ways"),
  ("https://www.motionpictures.org/2025/11/christopher-nolans-the-odyssey-an-attempt-to-break-new-cinematic-ground/", "MPA — интервью Нолана", "MPA — Nolan interview"),
 ]),
 ("g2", [
  ("https://uscatholic.org/articles/202607/nolans-the-odyssey-links-ancient-codes-to-christian-precepts/", "U.S. Catholic — ксения в фильме", "U.S. Catholic — xenia in the film"),
  ("https://blog.acton.org/archives/128627-christopher-nolans-un-greek-odyssey.html", "Acton Institute — «закон Зевса»", "Acton Institute — \"the law of Zeus\""),
  ("https://en.wikipedia.org/wiki/Xenia_(Greek)", "Википедия — ксения и Зевс Ксений", "Wikipedia — xenia and Zeus Xenios"),
  ("https://www.britannica.com/topic/xenia-sociology", "Britannica — ксения", "Britannica — xenia"),
 ]),
 ("g3", [
  ("https://classical-inquiries.chs.harvard.edu/a-sampling-of-comments-on-odyssey-rhapsody-8", "Г. Нэджи — конь как δόλος", "G. Nagy — the horse as δόλος"),
  ("https://continuum.fas.harvard.edu/odyssey-24/", "Г. Нэджи — расправа и амнистия", "G. Nagy — the slaughter and the amnesty"),
  ("https://www.britannica.com/topic/Odyssey-epic-by-Homer", "Britannica — структура поэмы", "Britannica — structure of the poem"),
  ("https://www.livius.org/sources/content/epic-cycle/returns/", "«Возвращения» (Ностой) — гнев богов на ахейцев", "The Nostoi — divine anger at the Achaeans"),
  ("https://bmcr.brynmawr.edu/2004/2004.02.24", "BMCR — о «Поэме о силе» Симоны Вейль", "BMCR — on Weil's The Poem of Force"),
  ("https://quoteinvestigator.com/2020/02/11/story/", "Quote Investigator — четыре сюжета Борхеса", "Quote Investigator — tracing Borges's four stories"),
  ("https://www.thecollector.com/cyclops-fossil-greek-myth/", "The Collector — черепа слонов и миф о циклопе", "The Collector — elephant skulls and the Cyclops myth"),
  ("https://www.theoi.com/Pontios/Skylla.html", "Theoi — Сцилла у Гомера", "Theoi — Homer's Scylla"),
  ("https://en.wikipedia.org/wiki/The_Odyssey_(2026_film)", "Википедия — «Одиссея» (2026), факты производства", "Wikipedia — The Odyssey (2026), production facts"),
 ]),
]
